/* 
 * This file is automatically generated by the build process
 * DO NOT EDIT!
 */

#include "Build.h"
#include <stdio.h>

const int VER_MAJOR = 0;
const int VER_MINOR = 1;
const int VER_PATCH = 0;

int getMajorVersion() { return VER_MAJOR; }
int getMinorVersion() { return VER_MINOR; }
int getReleaseVersion() { return VER_PATCH; }
int getBuildVersion() { return VER_BUILD; }

const char* getVersionLabel() {
   static char verStr[16];
#ifdef WIN32
   sprintf_s(verStr, 16, "%d.%d.%d.%d", VER_MAJOR, VER_MINOR, VER_PATCH, VER_BUILD);
#else
   snprintf(verStr, 16, "%d.%d.%d.%d", VER_MAJOR, VER_MINOR, VER_PATCH, VER_BUILD);
#endif
   return verStr;
}

