#!/bin/bash

usage() {
    echo "usage: apcctl <start|stop|restart|status> [process]"
    echo ""
    echo "APC control script -- Start, stop and monitor the APC processes"
    echo "  action : start, stop, restart, status"
    echo "  process: apc process name"
}

# Command line arguments

if [ -z "$1" ]; then
    usage
    exit 1
fi

action=$1
target=$2

# Handle action by passing to supervisorctl

case $action in
    start)
        # start the apc process
        if [ -z "$target" ]; then
            usage
        else
            supervisorctl start $target
        fi
        ;;

    stop)
        # stop the apc process
        if [ -z "$target" ]; then
            usage
        else
            supervisorctl stop $target
        fi
        ;;

    restart)
        # restart the apc process
        if [ -z "$target" ]; then
            usage
        else
            supervisorctl restart $target
        fi
        ;;

    status)
        supervisorctl status
        ;;

    *)  
        echo "error: unknown action '$action'"
        usage
        exit 1
esac
